### ISSUE TITLE
Doesn't work on Internet Explorer

### ISSUE THREAD

**Issue by 21110027781** [tjcafferkey/removeduplicates#1]
`function removeDuplicates(arr, key) {
    if (!(arr instanceof Array) || key && typeof key !== 'string') {
        return false;
    }
    if (key && typeof key === 'string') {
        return arr.filter((obj, index, arr) => {
            return arr.map(mapObj => mapObj[key]).indexOf(obj[key]) === index;
        });
    } else {
        return arr.filter(function(item, index, arr) {
            return arr.indexOf(item) == index;
        });
    }
}`

I can't run function on IE 11 (error messsage : Syntax error).
Something wrong in this code

`return arr.filter((obj, index, arr) => {
    return arr.map(mapObj => mapObj[key]).indexOf(obj[key]) === index;
});`

**Comment by tjcafferkey** [comment]
@21110027781 This is because the function in this repository is written in ES6. If you install the [npm package](https://www.npmjs.com/package/removeduplicates) you will get the transpiled code in ES5. Alternatively I've provided you with the ES5 code here which you can copy.

```javascript
function removeDuplicates(arr, key) {
    if (!(arr instanceof Array) || key && typeof key !== 'string') {
        return false;
    }

    if (key && typeof key === 'string') {
        return arr.filter(function (obj, index, arr) {
            return arr.map(function (mapObj) {
                return mapObj[key];
            }).indexOf(obj[key]) === index;
        });
    } else {
        return arr.filter(function (item, index, arr) {
            return arr.indexOf(item) == index;
        });
    }
}
```
